apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-02-25T23:24:28Z"
  labels:
    app: phpdeploy
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:ports:
          .: {}
          k:{"port":80,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl.exe
    operation: Update
    time: "2021-02-25T23:24:28Z"
  name: phpclusterservice
  namespace: newdev
  resourceVersion: "46552"
  selfLink: /api/v1/namespaces/newdev/services/phpclusterservice
  uid: c417f86d-1801-4fc0-be1e-ca961e4ac320
spec:
  clusterIP: 10.1.0.23
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: phpdeploy
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
