apiVersion: v1
kind: Service
metadata:
  labels:
    app: phpdeploy
  name: phpclusterservice
  namespace: newdev
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: phpdeploy
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
