apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aksday3-75ad"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aksday3-75ad"
  template:
    metadata:
      labels:
        app: "aksday3-75ad"
    spec:
      containers:
        - name: "aksday3-75ad"
          image: "aksday3acr.azurecr.io/aksday3"
          ports:
          - containerPort: 80