apiVersion: v1
kind: Service
metadata:
  labels:
    app: phpdeploy
  name: phpservice
  namespace: newdev
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31569
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: phpdeploy
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
