on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: aksday3acr.azurecr.io
        username: ${{ secrets.acr_aksday3acr_username }}
        password: ${{ secrets.acr_aksday3acr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t aksday3acr.azurecr.io/aksday3:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push aksday3acr.azurecr.io/aksday3:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksday3_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep newdev | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace newdev`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: newdev
        container-registry-url: aksday3acr.azurecr.io
        container-registry-username: ${{ secrets.acr_aksday3acr_username }}
        container-registry-password: ${{ secrets.acr_aksday3acr_password }}
        secret-name: aksday3dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: newdev
        manifests: |
          manifests/mysqlsecret.yaml
          manifests/mysqlset.yaml
          manifests/mysqlservice.yaml
          manifests/phpsecret.yaml
          manifests/aksspclass.yaml
          manifests/phpdeploy.yaml
          manifests/phpservice.yaml
          manifests/deployment.yml
          manifests/service.yml
        images: |
          aksday3acr.azurecr.io/aksday3:${{ github.sha }}
        imagepullsecrets: |
          aksday3dockerauth
